apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servicesync.fullname" . }}
  labels:
    {{- include "servicesync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "servicesync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servicesync.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "servicesync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{.Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SS_RENAME_SERVICE
              value: {{.Values.env.destinationService}}
            - name: SS_SERVICE
              value: {{.Values.env.sourceService}}
            - name: SS_SOURCE_KUBE_CONFIG
              value: {{.Values.env.sourceKConfig}}
            - name: SS_SOURCE_NAMESPACE
              value: {{.Values.env.sourceNamespace}}
            - name: SS_DESTINATION_NAMESPACE
              value: {{.Values.env.destinationNamespace}}
          volumeMounts:
            - name: kube-config
              mountPath: /etc/config/kubeconfig
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: kube-config
          configMap:
            name: ss-source-kubeconfig
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
